Boolean Masks: Generate 100 random numbers, find numbers divisible by 3, and replace them with -1.

In [11]:
import numpy as np

# Generate 100 random numbers
rand_nums = np.random.randint(1, 101, 100)

print("Before Mask: \n", rand_nums)

# Create boolean mask to find numbers divisible by 3
mask = rand_nums % 3 == 0

# Replace the numbers divisible by 3 with -1
rand_nums[mask] = -1

print("\n", "After Mask: \n", rand_nums)

Before Mask: 
 [36 89  4 19 42 65 69  2  7 80 87 25 61 77 54 36 75 47 67  4 17 85 25  8
 65 34 90  3 94 87 77 79 37  8 69 61 56 72 41 21 44 36 96  1  1 11 37 54
 47 67 30 85 59 95  7 47 59 23 37 67 85 95 79 90 26 75 20 92  4 61 76 18
 63 91 99 80 89 77 53 26 95  3 80 72 34 24 50 63 77 41 17 65 78 16 22 78
 78 24 21  5]

 After Mask: 
 [-1 89  4 19 -1 65 -1  2  7 80 -1 25 61 77 -1 -1 -1 47 67  4 17 85 25  8
 65 34 -1 -1 94 -1 77 79 37  8 -1 61 56 -1 41 -1 44 -1 -1  1  1 11 37 -1
 47 67 -1 85 59 95  7 47 59 23 37 67 85 95 79 -1 26 -1 20 92  4 61 76 -1
 -1 91 -1 80 89 77 53 26 95 -1 80 -1 34 -1 50 -1 77 41 17 65 -1 16 22 -1
 -1 -1 -1  5]


Fancy Indexing: Extract every alternate row from a 5×5 matrix.

In [13]:

# Generate numbers 1-25 in a 5x5 matrix
nums = np.arange(1, 26).reshape(5, 5)
print("Full Array: \n", nums)

# Extract alternating rows by changing the step index

print("\n", nums[::2])

Full Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


Sorting: Generate a 10×10 matrix and sort by first column.

In [25]:
# Generate 100 random numbers in a 10x10 array
nums = np.random.randint(1, 101, (10,10))

print("Full Array: \n", nums)

sorted_col = nums[nums[:, 0].argsort()]

print("Sorted Column: \n", sorted_col)

Full Array: 
 [[96 43 19 54 38 40 11 22 47 98]
 [59 32 25 89 45 77 16 46 92 74]
 [69 46 71 28 14 78 73  9 98 65]
 [70 17 80 53 37 16 90 14 69 50]
 [ 8 49 49  7 93 63 15 70 45 57]
 [47 37 23 77 11 54 56 40  6 90]
 [26 44 41 11 65 85 90 31 51 71]
 [33 71 90 50 59 52 86 13 27 92]
 [41 38 29 45 50 13 66  8 86  5]
 [78 34 33 63 48 57 23 30 43 37]]
Sorted Column: 
 [[ 8 49 49  7 93 63 15 70 45 57]
 [26 44 41 11 65 85 90 31 51 71]
 [33 71 90 50 59 52 86 13 27 92]
 [41 38 29 45 50 13 66  8 86  5]
 [47 37 23 77 11 54 56 40  6 90]
 [59 32 25 89 45 77 16 46 92 74]
 [69 46 71 28 14 78 73  9 98 65]
 [70 17 80 53 37 16 90 14 69 50]
 [78 34 33 63 48 57 23 30 43 37]
 [96 43 19 54 38 40 11 22 47 98]]


4.Objective:
Use NumPy to analyze rainfall data and extract meaningful insights using Boolean masking, fancy indexing, sorting, and structured arrays.

Dataset:
You are provided with an array representing daily rainfall (in mm) over a year in a fictional city:

import numpy as np

np.random.seed(42)

rainfall = np.random.gamma(shape=2.0, scale=2.0, size=365)  # Synthetic daily rainfall data

rainfall[np.random.choice(365, 100, replace=False)] = 0  # 100 dry days

In [29]:
import numpy as np

np.random.seed(42)

rainfall = np.random.gamma(shape=2.0, scale=2.0, size=365)  # Synthetic daily rainfall data

rainfall[np.random.choice(365, 100, replace=False)] = 0  # 100 dry days

rainfall

array([ 0.        ,  2.98892946,  0.        ,  2.76460459,  0.        ,
        0.        ,  2.262156  ,  4.93962895,  3.99792053,  0.43182989,
        1.34248457,  4.21233127,  0.        ,  2.78370437,  2.11605488,
        3.62801508,  2.01056896,  2.63548276,  3.29860496,  1.28027461,
        5.94012019,  1.07036289,  0.94558689,  3.86790084,  5.62670762,
        3.79567115,  3.04355835,  0.        ,  2.27981966,  0.        ,
        4.24208788,  2.43463763,  1.87321306,  5.17523791,  6.76688335,
        6.36241956,  1.6020941 ,  0.        ,  2.24286994,  2.87657623,
        5.90217705,  8.20452491,  0.        ,  1.92968925,  0.        ,
        9.22507907,  3.5631772 ,  0.        ,  2.79770522,  0.        ,
        1.65126347,  0.        ,  6.29954479,  4.25625523,  3.59032168,
        6.51202713,  1.82937157,  0.        ,  4.15786061,  0.        ,
        0.85169115,  2.36092283,  2.93399674,  4.48921108,  0.        ,
        0.        ,  0.42821016,  0.        ,  3.49127806, 14.59

1. Boolean Arrays & Masks (Section 2.06)
Basic Rainy Day Count:

Use a Boolean mask to find how many days had rain (i.e., rainfall > 0 mm).

In [32]:

rainy_days_mask  = rainfall > 0

rainy_days_count = np.sum(rainy_days_mask)

print(rainy_days_count, "days")

265 days


Heavy Rain Days:

Find the percentage of days where rainfall exceeded 5 mm.


In [37]:
# Get the number of heavy rainfall days
heavyrain_mask = rainfall > 5

# Calculate the percentage of heavy rainfall days
heavyrain_ntile = np.mean(heavyrain_mask)

print(heavyrain_ntile * 100, "%")

20.0 %


Dry Spells:

Find the longest consecutive sequence of dry days (rainfall == 0).

In [42]:
dry_days_mask = rainfall == 0

longest_dry_days = 0
current_dry_streak = 0

for day in dry_days_mask:
    if day: # Since dry days in the mask are 1, this will be true
        current_dry_streak += 1
        # Update the longest streak if the current streak is longer
        longest_dry_days = max(longest_dry_days, current_dry_streak)
    else: 
        # We encountered a day in which it rained, reset the streak to 0
        current_dry_streak = 0
    
print(longest_dry_days, "dry days in a row.")


5 dry days in a row.


2. Fancy Indexing (Section 2.07)
Top Rainfall Days:

Find the 10 wettest days of the year using fancy indexing.

In [ ]:
sorted_indices = np.argsort(rainfall)[::-1]  # Sort in descending order
rainiest_days = rainfall[sorted_indices[:10]] # Extract the values from the sorted indices

print(rainiest_days)

[14.59599558 13.5930644  12.36345195 12.18019244 11.98741328 10.90674978
 10.90319363 10.84415104 10.23008331  9.86269307]



Monthly Averages:

Assume the data starts on January 1st. Compute the average monthly rainfall using fancy indexing.


In [59]:
# Array that contains the # of days in a month from January->December
days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])
monthly_averages = []

start_idx = 0

for days_this_month in days_in_month:
    end_idx = start_idx + days_this_month # Determine the ending index that count towards this month
    month_rainfall = rainfall[start_idx:end_idx] # Splice from start of the month to the end
    monthly_averages.append(np.mean(month_rainfall)) # Calculate the average for this month
    start_idx = end_idx # Update to point to the start of the next month

# Print resulting averages
for idx, avg_rainfall in enumerate(monthly_averages):
    print(f"Month {idx}: {avg_rainfall:.2f} mm")

Month 0: 2.31 mm
Month 1: 3.19 mm
Month 2: 3.23 mm
Month 3: 3.37 mm
Month 4: 2.55 mm
Month 5: 3.66 mm
Month 6: 2.57 mm
Month 7: 2.38 mm
Month 8: 3.04 mm
Month 9: 2.55 mm
Month 10: 2.67 mm
Month 11: 2.85 mm


3. Sorting (Section 2.08)
Sorting Rainfall Data:

Sort the rainfall array in ascending order and find the median rainfall value.


In [94]:
sorted_arr = np.sort(rainfall)
median = np.median(sorted_arr)
print(f"Median: {median:.2f} mm")

Median: 49.45 mm


Percentile Analysis:

Find the 90th percentile of rainfall (i.e., the rainfall value above which only 10% of days occur).



In [64]:
percentile_90 = np.percentile(rainfall, 90)

print(f"The 90th percentile of rainfall is: {percentile_90:.2f} mm")

The 90th percentile of rainfall is: 6.46 mm


4. Structured Data (Section 2.09)
Creating a Structured Array:

    Create a structured NumPy array where each entry contains:

        day (integer, 1 to 365)

        rainfall (float, in mm)

        is_rainy (Boolean, True if rainfall > 0)

In [67]:
#day : integer4bytes
#rainfall : float4bytes
#is_rainy : boolean

# Define the data
dtype = [('day', 'i4'), ('rainfall', 'f4'), ('is_rainy', 'b')]

# Generate data
days = np.arange(1, 366)
rainfall = np.random.uniform(0, 100, 365) # Generate 365 values ranging from 0-100
is_rainy = rainfall > 0 # Mask for determining if it is a rainy day

# Structured weather data
weather_data = np.zeros(365, dtype=dtype)

# Assign values to structured array
weather_data['day']= days
weather_data['rainfall'] = rainfall
weather_data['is_rainy'] = is_rainy

print(weather_data)

[(  1, 25.54135   , 1) (  2, 26.07133   , 1) (  3,  6.925431  , 1)
 (  4, 95.98265   , 1) (  5, 47.82553   , 1) (  6, 89.58146   , 1)
 (  7, 32.22155   , 1) (  8, 12.523357  , 1) (  9, 47.433613  , 1)
 ( 10, 11.395663  , 1) ( 11, 48.60155   , 1) ( 12, 92.02972   , 1)
 ( 13, 52.076813  , 1) ( 14, 61.64997   , 1) ( 15, 15.663844  , 1)
 ( 16,  4.373563  , 1) ( 17, 11.080796  , 1) ( 18, 59.853157  , 1)
 ( 19,  9.50117   , 1) ( 20, 37.59929   , 1) ( 21, 55.009193  , 1)
 ( 22, 38.86528   , 1) ( 23, 16.36838   , 1) ( 24, 27.379131  , 1)
 ( 25, 92.83176   , 1) ( 26, 67.59823   , 1) ( 27, 49.604782  , 1)
 ( 28,  1.271489  , 1) ( 29, 99.24154   , 1) ( 30, 67.14549   , 1)
 ( 31, 31.692247  , 1) ( 32, 87.926865  , 1) ( 33, 25.843163  , 1)
 ( 34, 54.401657  , 1) ( 35, 63.607075  , 1) ( 36, 22.106337  , 1)
 ( 37, 97.83973   , 1) ( 38, 74.81919   , 1) ( 39, 55.781322  , 1)
 ( 40, 18.05946   , 1) ( 41,  5.385821  , 1) ( 42, 32.00598   , 1)
 ( 43, 75.31873   , 1) ( 44, 26.93313   , 1) ( 45, 53.955624  

Filtering Data with Structured Arrays:

Use Boolean masks on the structured array to extract all rainy days and compute their average rainfall.

In [79]:
rainy_days_mask = weather_data['rainfall'] > 0 # Mask where rainfall is greater than 0 

# Use the mask to filter the rainfall values of the rainy days
rainy_days_rainfall = weather_data['rainfall'][rainy_days_mask]

# Calculate the average rainfall
avg_rainfall = np.mean(rainy_days_rainfall)

print(f"Average rainfall on rainy days: {avg_rainfall:.2f}")


Average rainfall on rainy days: 49.07


Sorting Structured Data:

Sort the structured array by rainfall and print the top 5 rainiest days.


In [89]:
sorted_rainfall = np.sort(weather_data['rainfall'])[::-1]

print(f"Top 5 Rainiest Days: {sorted_rainfall[:5]}")

Top 5 Rainiest Days: [99.70782 99.24154 99.17426 99.11264 98.8416 ]
