💡 Exercise 1: Why is NumPy Faster?

🔹 Write a Python program in PyCharm that compares the speed of Python lists vs. NumPy arrays for squaring 1 million numbers.

In [3]:
import numpy as np
import time

n = 1000000

# Lists of numbers
numbers = list(range(n)) 
np_numbers = np.arange(n)

# Measure the time it takes for a Python list
start_time = time.time()
squared_list = {x**2 for x in numbers}
end_time = time.time()

list_time = end_time - start_time

# Measure the time it takes for a NumPy list
start_time = time.time()
squared_numpy = np_numbers**2
end_time = time.time()

np_time = end_time - start_time

# Log the elapsed time
print(f"Python list time : {list_time}")
print(f"NumPy time : {np_time}")


Python list time : 0.1462099552154541
NumPy time : 0.0018837451934814453


📝 Question: Which approach is faster? Why?



NumPy appears to be 80x faster than Python lists. This is because NumPy arrays are implemented in C and which is then optimized for speed and efficiency.
On the otherhand, Python lists are collections of pointers that point to native Python objects which are not not optimized for numerical efficiency.

Another difference is how the operation is applied to NumPy arrays and Python lists.

Squaring 1 million numbers in a Python list requires looping over all elements of the list and applying the operation to a single element at a time.
NumPy arrays support vectorization which allows operations to be performed across the entire array simultaneously. 

💡 Exercise 2: Create Different Arrays
🔹 Create a 4x4 matrix of random numbers.
🔹 Print its shape, size, and dimensions.

In [ ]:
# Random 4x4 matrix
random_matrix = np.random.rand(4, 4)

print("Random 4x4 Matrix:")
print(random_matrix)

# Print shape, size, and dimensions
print("\nShape:", random_matrix.shape)
print("Size:", random_matrix.size)
print("Dimensions:", random_matrix.ndim)

Random 4x4 Matrix:
[[0.00549808 0.54119127 0.66281338 0.79535262]
 [0.12445965 0.41719279 0.92787339 0.99620133]
 [0.58178298 0.47879929 0.79433896 0.18405995]
 [0.80418124 0.49886247 0.22436498 0.60499862]]

Shape: (4, 4)
Size: 16
Dimensions: 2


💡 Exercise 3: Random Data Generation

🔹 Create a 3x3 identity matrix.

🔹 Create a 1D array of 20 random integers between 1 and 100.



In [12]:
identity_matrix = np.identity(3)
print(identity_matrix)

# 1D array of 20 random integers between 1 and 100.

random_int = np.random.randint(1, 101, size=20)
print(random_int)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[57 44  2  3 18 96 70 15 31 97 23  7 10 39  3 70 45  2 62 45]


💡 Exercise 4: Array Slicing
🔹 Given a 5x5 matrix of numbers from 1 to 25, extract:

The third row
The last two columns
A 3x3 submatrix from the center


In [33]:

# 5x5 matirx of numbers from 1 to 25
matrix = np.arange(1, 26).reshape(5,5)

print("Entire matrix \n", matrix)

print("Third Row: ", matrix[2])
print("Last two columns: \n", matrix[ :, -2:])

sub_matrix = matrix[1:4, 1:4]
print("A 3x3 submatrix from the center: \n", sub_matrix)


Entire matrix 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Third Row:  [11 12 13 14 15]
Last two columns: 
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]
A 3x3 submatrix from the center: 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


💡 Exercise 5: Reshaping Practice

🔹 Reshape a 1D array of 20 elements into a 4x5 matrix.



In [37]:
original_matrix = np.arange(1, 21)

augmented_matrix = original_matrix.reshape(4, 5)

print("Original Matrix: \n",original_matrix)
print("Reshaped Matrix: \n", augmented_matrix)

Original Matrix: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped Matrix: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
